# Generated by Django 4.1.6 on 2023-05-01 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schtools', '0001_initial'),
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='cart',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='schtools.cart'),
        ),
        migrations.AddField(
            model_name='student',
            name='schedules',
            field=models.ManyToManyField(to='schtools.schedule'),
        ),
        migrations.AddField(
            model_name='advisor',
            name='schedules',
            field=models.ManyToManyField(blank=True, to='schtools.schedule'),
        ),
        migrations.AddField(
            model_name='advisor',
            name='students',
            field=models.ManyToManyField(to='login.student'),
        ),
    ]
