# Generated by Django 4.1.6 on 2023-04-03 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
