# Generated by Django 4.1.6 on 2023-04-16 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_class_delete_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='class_section',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='class',
            name='crse_id',
            field=models.IntegerField(default=-1),
        ),
    ]
